# Generated by Django 4.2.6 on 2024-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_dercription', models.IntegerField(choices=[(0, 'Sunny'), (1, 'Rain'), (2, 'Cloudy'), (3, 'Snow')], default=0)),
                ('temparature', models.FloatField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
    ]
